package parmenidianEnumerations;

public enum Metric_Enums {
	
	VERTEX_IN_DEGREE,
	VERTEX_OUT_DEGREE,
	VERTEX_DEGREE,
	VERTEX_BETWEENNESS,
	CLUSTERING_COEFFICIENT,
	EDGE_BETWEENNESS,
	GRAPH_DIAMETER,
	NUMBER_OF_VERTICES,
	NUMBER_OF_EDGES,
	NUMBER_OF_CONNECTED_COMPONENTS,
	NUMBER_OF_VERTICES_IN_GCC,
	NUMBER_OF_EDGES_IN_GCC

}
